azure:
  endpoint: https://dsu-formrecognizer.cognitiveservices.azure.com/
  service_url: formrecognizer/v2.0-preview/custom/models/
  apim_key: f92a702ac2ba405a99c3a35067055f32
  prefix: 8774_training
  source: https://dsuorder.blob.core.windows.net/formrecognizer?sv=2019-02-02&ss=bfqt&srt=sco&sp=rwdlacup&se=2020-04-14T14:19:27Z&st=2020-04-14T06:19:27Z&spr=https&sig=NPwS3wSi9Tj8cUcYsOXZWBXhKbQHc4RfP6hPkyotLrU%3D

request: 
  n_tries: 15
  n_try: 0
  wait_sec: 5
  max_wait_sec: 60